version: '3.7'

services:
  strapi:
    container_name: strapi
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 1337:1337
